import type { Rack, User } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '123-456-7890',
    businessName: 'JD Retail',
    avatarUrl: 'https://placehold.co/100x100.png',
  },
  {
    id: 'user-2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '098-765-4321',
    avatarUrl: 'https://placehold.co/100x100.png',
  },
];

export const mockRacks: Rack[] = [
  {
    id: 'rack-1',
    title: 'Prime Aisle End-Cap in High-Traffic Supermarket',
    description: 'Excellent visibility at the end of a busy aisle. Perfect for new product launches. Comes with optional branding panels. High footfall guaranteed.',
    owner: mockUsers[0],
    location: 'Downtown, Metro City',
    pincode: '110001',
    weeklyRent: 2500,
    dailyFootfall: 1200,
    weeklyFootfall: 8400,
    dailySales: 15000,
    weeklySales: 105000,
    photos: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    status: 'Available',
  },
  {
    id: 'rack-2',
    title: 'Boutique Front Window Shelf',
    description: 'Charming shelf space in the front window of a trendy boutique. Ideal for artisanal goods, jewelry, or accessories. Attracts fashion-conscious shoppers.',
    owner: mockUsers[1],
    location: 'Arts District, Creative Town',
    pincode: '400050',
    weeklyRent: 1800,
    dailyFootfall: 400,
    weeklyFootfall: 2800,
    dailySales: 8000,
    weeklySales: 56000,
    photos: ['https://placehold.co/600x400.png'],
    status: 'Available',
  },
  {
    id: 'rack-3',
    title: 'Checkout Counter Display at Cafe',
    description: 'Compact display space right at the checkout counter. Perfect for impulse buys like snacks, drinks, or small gift items. Constant queue of customers.',
    owner: mockUsers[0],
    location: 'Central Park, Metro City',
    pincode: '110001',
    weeklyRent: 900,
    dailyFootfall: 800,
    weeklyFootfall: 5600,
    dailySales: 5000,
    weeklySales: 35000,
    photos: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    status: 'Rented',
  },
  {
    id: 'rack-4',
    title: 'Full Gondola in Electronics Store',
    description: 'A full gondola rack in a busy electronics hub. Suitable for gadgets, mobile accessories, or gaming merchandise. High-intent buyers.',
    owner: mockUsers[1],
    location: 'Tech Hub, Silicon Valley',
    pincode: '560034',
    weeklyRent: 3500,
    dailyFootfall: 950,
    weeklyFootfall: 6650,
    dailySales: 25000,
    weeklySales: 175000,
    photos: ['https://placehold.co/600x400.png'],
    status: 'Available',
  },
    {
    id: 'rack-5',
    title: 'Shelf in Organic Food Mart',
    description: 'A dedicated shelf in a popular organic food store. Great for healthy snacks, supplements, or eco-friendly products. Targets health-conscious consumers.',
    owner: mockUsers[0],
    location: 'Greenway, Wellness City',
    pincode: '600028',
    weeklyRent: 1500,
    dailyFootfall: 600,
    weeklyFootfall: 4200,
    dailySales: 10000,
    weeklySales: 70000,
    photos: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    status: 'Available',
  },
  {
    id: 'rack-6',
    title: 'Bookstore Entrance Display Stand',
    description: 'A standalone display stand near the entrance of a popular bookstore. Excellent for magazines, stationery, or author promotions.',
    owner: mockUsers[1],
    location: 'University Area, Scholar Town',
    pincode: '400098',
    weeklyRent: 1200,
    dailyFootfall: 700,
    weeklyFootfall: 4900,
    dailySales: 6000,
    weeklySales: 42000,
    photos: ['https://placehold.co/600x400.png'],
    status: 'Rented',
  },
];
